### ISSUE TITLE
Sensor not updating

### ISSUE THREAD

**Issue by itm1960** [arsaboo/homeassistant-config#8]
Hi
This component looks like exactly what I am looking for, but I am having problems getting my life360 sensor to update.
I have copied life360.py to my custom_components/sensor folder, and have the following entries in my configuration.yaml:
```
mqtt:
  embedded:
    listeners:
      default:
        max-connections: 5000
        bind: 192.168.1.36:1883
        type: tcp
      ws-1:
          bind: 192.168.1.36:8087
          type: ws
    auth:
      plugins: ['auth.anonymous']
      allow-anonymous: true
  broker: 192.168.1.36
  port: 1883
  
sensor:
  - platform: life360
    name: life360_ian
    username: "mylife360user@gmail.com"
    password: "mylife360password"
    mqtt_topic: "life360/ian"

device_tracker:
  - platform: owntracks
```
I can see the life360 sensor on my HA console, but it never gets updated. I'm running HA v0.65.0 on Lubuntu 16.10. MQTT seems to be running OK.
The only part of the instructions in your code that I didn't understand was the part that said I needed to copy the life360 package from your repository - I don't know what this means?(!)

Have you any idea why my life360 sensor is not getting updated?
